name: Development Crystal CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Build docs
      run: crystal docs
